if filereadable(expand("~/.vimrc.bundles"))
source ~/.vimrc.bundles
endif

syn on " 语法高亮

set bs=2 " 在insert模式下用退格键删除
set nocompatible " Disable vi-compatibility 
set laststatus=2 " 总是显示状态行
set expandtab    " 以下三个配置配合使用, 设置tab和缩进空格数
set shiftwidth=4
set tabstop=4

"set cursorline " 为光标所在行加下划线
set number	" 显示行号
set autoread    " 文件在vim之外修改过, 自动重新读入

set hls " 检索时高亮显示
"set foldmethod=marker " 代码折叠
"set fdm=syntax
"set fdm=indent
let g:ycm_global_ycm_extra_conf='~/.vim/.ycm_extra_conf.py'


set encoding=utf-8 " Necessary to show Unicode glyphs
set t_Co=256 " Explicitly tell Vim that the terminal supports 256 colors

" NERDTree
map <F5> :NERDTreeToggle<CR>
"autocmd vimenter * NERDTree " 导致YCM 不能正常工作
"set autochdir

" Tagbar
nmap <F6> :TagbarToggle<CR>

" a.vim
nnoremap <silent> <F8> :A<CR>  "头文件与cpp/c文件切换
nnoremap <silent> <F9> :AS<CR>  "横向切割头文件与cpp/c文件切换
nnoremap <silent> <F10> :AV<CR>  "纵向切割头文件与cpp/c文件切换 ALT + <F9>

" ctags
map <F1> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
map <F2> :!cscope -Rbkq <CR>

"filetype plugin indent on

let g:molokai_original = 1
let g:rehash256 = 1
